# Generated by Django 6.0.2 on 2026-05-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('Mobiles', 'Mobiles'), ('Fashion', 'Fashion'), ('Electronics', 'Electronics'), ('Home', 'Home'), ('Beauty', 'Beauty'), ('Grocery', 'Grocery'), ('Books', 'Books'), ('Appliances', 'Appliances')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
